const allPhones = [
  {
    id: "1",
    img: "/assets/iphone12.jpg",
    name: "iPhone 12",
    brand: "Apple",
    price: 800,
    memory: 64,
    color: "black",
  },
  {
    id: "2",
    img: "/assets/s21.jpg",
    name: "Samsung Galaxy S21",
    brand: "Samsung",
    price: 750,
    memory: 128,
    color: "blue",
  },
  {
    id: "3",
    img: "/assets/s21.jpg",
    name: "Pixel 5",
    brand: "Google",
    price: 600,
    memory: 128,
    color: "white",
  },
  {
    id: "4",
    img: "/assets/s21.jpg",
    name: "Xiaomi 11 Lite",
    brand: "Xiaomi",
    price: 400,
    memory: 64,
    color: "red",
  },
  {
    id: "5",
    img: "/assets/s21.jpg",
    name: "OnePlus 9",
    brand: "OnePlus",
    price: 850,
    memory: 128,
    color: "gray",
  },
  {
    id: "6",
    img: "/assets/s21.jpg",
    name: "Huawei P40",
    brand: "Huawei",
    price: 700,
    memory: 256,
    color: "purple",
  },
  {
    id: "7",
    img: "/assets/s21.jpg",
    name: "Sony Xperia 5 III",
    brand: "Sony",
    price: 900,
    memory: 128,
    color: "green",
  },
  {
    id: "8",
    img: "/assets/s21.jpg",
    name: "Pixel 5",
    brand: "Google",
    price: 600,
    memory: 128,
    color: "white",
  },
  {
    id: "9",
    img: "/assets/s21.jpg",
    name: "Nokia 7.2",
    brand: "Nokia",
    price: 400,
    memory: 64,
    color: "yellow",
  },
  {
    id: "10",
    img: "/assets/s21.jpg",
    name: "Google Pixel 6",
    brand: "Google",
    price: 600,
    memory: 128,
    color: "black",
  },
  {
    id: "11",
    img: "/assets/s21.jpg",
    name: "Xiaomi Mi 11T",
    brand: "Xiaomi",
    price: 450,
    memory: 64,
    color: "white",
  },
  {
    id: "12",
    img: "/assets/s21.jpg",
    name: "Pixel 5",
    brand: "Google",
    price: 600,
    memory: 128,
    color: "white",
  },
  {
    id: "13",
    img: "/assets/s21.jpg",
    name: "Honor 10 Lite",
    brand: "Honor",
    price: 400,
    memory: 64,
    color: "green",
  },
  {
    id: "14",
    img: "/assets/s21.jpg",
    name: "Honor 10 Lite",
    brand: "Honor",
    price: 400,
    memory: 64,
    color: "green",
  },
];

export default allPhones;
