[
  {
    name: "iPhone 12",
    brand: "Apple",
    price: 800,
    memory: 64,
    color: "black",
  },
  {
    name: "Samsung Galaxy S21",
    brand: "Samsung",
    price: 750,
    memory: 128,
    color: "blue",
  },
  {
    name: "Pixel 5",
    brand: "Google",
    price: 600,
    memory: 128,
    color: "white",
  },
  {
    name: "Xiaomi 11 Lite",
    brand: "Xiaomi",
    price: 400,
    memory: 64,
    color: "red",
  },
  {
    name: "OnePlus 9",
    brand: "OnePlus",
    price: 850,
    memory: 128,
    color: "gray",
  },
  {
    name: "Huawei P40",
    brand: "Huawei",
    price: 700,
    memory: 256,
    color: "purple",
  },
  {
    name: "Sony Xperia 5 III",
    brand: "Sony",
    price: 900,
    memory: 128,
    color: "green",
  },
  {
    name: "LG V70 ThinQ",
    brand: "LG",
    price: 750,
    memory: 128,
    color: "orange",
  },
  {
    name: "Nokia 7.2",
    brand: "Nokia",
    price: 400,
    memory: 64,
    color: "yellow",
  },
  {
    name: "Google Pixel 6",
    brand: "Google",
    price: 600,
    memory: 128,
    color: "black",
  },
  {
    name: "Xiaomi Mi 11T",
    brand: "Xiaomi",
    price: 450,
    memory: 64,
    color: "white",
  },
  {
    name: "Oppo Reno 4",
    brand: "Oppo",
    price: 650,
    memory: 256,
    color: "red",
  },
  {
    name: "vivo X70",
    brand: "vivo",
    price: 500,
    memory: 128,
    color: "blue",
  },
  {
    name: "Honor 10 Lite",
    brand: "Honor",
    price: 400,
    memory: 64,
    color: "green",
  },
];
